multi arch
OpenLiberty/sample-getting-started pull request #81
Opened 2023-03-24 14:42 UTC by davco01a

2023-03-25 02:25 UTC, mbroz2 approved these changes

2023-03-28 12:19 UTC, websterc87 requested changes

2023-03-28 12:19 UTC, websterc87 commented on ebcDockerBuilderLGS.jenkinsfile
> +  dir('websphere-liberty-operator') {
This will need updating

2023-03-28 12:19 UTC, websterc87 commented on Makefile
> +build-sample:
Any reason we have this make file, could this not just be a shell script. Reduce the technologies used.

2023-03-28 12:19 UTC, websterc87 commented on .one-pipeline.yaml
> +      DIGEST="$(skopeo inspect docker://$IMAGE | grep Digest | grep -o 'sha[^\"]*')"
Does this work if you havent built the image on the same machine. Im not sure how it can find it.

2023-03-28 12:19 UTC, websterc87 commented on .one-pipeline.yaml
> +    # # build P and Z
Obviously needs comments back in.

2023-03-28 13:51 UTC, davco01a commented on .one-pipeline.yaml
> +        docker run -d --name getting-started-sample -p 9080:9080 $PROD_IMAGE
adding request orchestrator logic to handle

2023-03-29 13:34 UTC, closed without merging