WIP: Multi arch
OpenLiberty/sample-getting-started pull request #83
Opened 2023-03-29 13:34 UTC by davco01a

Multi architecture build and automated test of Liberty Sample

2023-03-29 14:46 UTC, halim-lee commented on ebcDockerBuilderLGS.jenkinsfile
> +      string(name: 'PIPELINE_OPERATOR_IMAGE', defaultValue: "cp/liberty-getting-started-sample", description: 'namespace to push image to in registry'),
string(name: 'IMAGE', defaultValue: "cp.stg.icr.io/cp/liberty-getting-started-sample", description: 'namespace to push image to in registry'),

2023-03-29 14:47 UTC, halim-lee commented on ebcDockerBuilderLGS.jenkinsfile
> +      string(name: 'OPM_VERSION', defaultValue: "4.10", description: 'Redhat CLI OPM version'),
can be removed

2023-03-29 14:47 UTC, halim-lee commented on ebcDockerBuilderLGS.jenkinsfile
> +      string(name: 'PIPELINE_REGISTRY', defaultValue: "cp.stg.icr.io", description: 'staging registry to push images to')
--> string(name: 'CONTAINER_REGISTRY', defaultValue: "cp.stg.icr.io", description: 'staging registry to push images to')

2023-03-29 14:48 UTC, halim-lee commented on scripts/pipeline/request-ciorchestrator.sh
> +            "PIPELINE_REGISTRY": "${PIPELINE_REGISTRY}",
--> "CONTAINER_REGISTRY": "${CONTAINER_REGISTRY}",

2023-03-29 14:48 UTC, halim-lee commented on scripts/pipeline/request-ciorchestrator.sh
> +            "PIPELINE_OPERATOR_IMAGE": "${PIPELINE_OPERATOR_IMAGE}",
"IMAGE": "${IMAGE}",

2023-03-29 14:49 UTC, halim-lee commented on scripts/pipeline/request-ciorchestrator.sh
> +            "OPM_VERSION": "${OPM_VERSION}",
can be removed

2023-03-29 14:50 UTC, halim-lee commented on ebcDockerBuilderLGS.jenkinsfile
> +}
can be removed

2023-03-29 14:52 UTC, halim-lee commented on ebcDockerBuilderLGS.jenkinsfile
> +               gitCloneAndStash();
can be removed

2023-03-29 15:02 UTC, halim-lee commented on .one-pipeline.yaml
> +    CONTAINER_REGISTRY=$CONTAINER_REGISTRY
Could we remove them?

2023-03-30 15:39 UTC, websterc87 requested changes

2023-03-30 15:39 UTC, websterc87 commented on scripts/pipeline/request-ciorchestrator.sh
> +        "ecosystemRouting": "prod",
While testing you likely want this to be dev, otherwise you will need to push the jenkins jobs to early

2023-04-24 14:26 UTC, websterc87 submitted a review, later dismissed
LGTM

2023-04-24 19:03 UTC, mbroz2 approved these changes
We could probably do without the makefile, but it all looks good.

2023-04-24 19:03 UTC, merged